apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xla9osk9t-java-springboot
  janus-idp.io/tekton: xla9osk9t-java-springboot
  backstage.io/kubernetes-id: xla9osk9t-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xla9osk9t-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
